[package]
name = "rust-htmx"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "1.3.58", features = ["static-files"] }
poem-openapi = { version = "3.0.5", features = ["swagger-ui"] }
tokio = { version = "1.33.0", features = ["full"] }
